### ISSUE TITLE
Проверяем рабочий процесс

### ISSUE THREAD

**Issue by mozolev** [htmlacademy-adaptive/125911-pink#1]
# :clipboard: Задание состоит из нескольких шагов:

- [x]  **1.** Сделайте форк личного проекта, ссылка на который есть в правой колонке интерфейса участника. Если ссылки нет, то надо немного подождать, пока наш робот создаст репозиторий вашего проекта.

- [x] **2.** В форке личного проекта создайте ветку **`module1-task1`**.

- [x] **3.** В этой ветке внесите изменения в файл **`Readme.md`** (с помощью любого текстового редактора): укажите своего наставника.

- [x] **4.** Создайте пулреквест из ветки **`module1-task1`** вашего форка в мастер-репозиторий и нажмите зелёную кнопку «Всё выполнил, можно проверять» в интерфейсе интенсива.

> 
Если наставник попросит внести дополнительные изменения, то их нужно вносить в форке, коммитить новые изменения и синхронизовать ваш форк. Новый пулреквест создавать не нужно. Все изменения автоматически появятся в уже созданном пулреквесте.

> Задание можно отправить на проверку только после привязки к нему пулреквеста, отправленного из ветки **`module1-task1`**.

**Comment by aalexeev239** [comment]
closed #2
